<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN" Id="{e0e3ca32-8ac9-4c9e-aa5e-a282e7142877}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
// ***********************************************************************************
//
// USI Mendrisio, Largo Bernasconi 2, CH-6850 Mendrisio
// ETH Zurich, Building HIF E26, Laura-Hezner-Weg 7, CH-8093 Zürich
// 
// ***********************************************************************************
// 
// PROJECT     :  Clay Printing Controller
// FUNCTION    :  Main 
// AUTHOR      :  WeiTing Chen
// EMAIL       :  chen@mesh.ch
// Copyright   :  USI FMAA Mendrisio(CH) 2025
//
// ***********************************************************************************


// Control Mode select 
P_Control_Mode();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="28" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="23" Count="0" />
      <LineId Id="7" Count="1" />
      <LineId Id="10" Count="2" />
      <LineId Id="22" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="15" Count="4" />
      <LineId Id="24" Count="1" />
      <LineId Id="2" Count="0" />
      <LineId Id="26" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>