<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="P_Laptop_Operate" Id="{900ed715-74f5-4bfb-958b-6045f4772707}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Laptop_Operate
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="P_Laptop_Operate">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>