<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="P_Robot_Operate" Id="{d6914ce3-ccac-49af-81dd-d937c420ed91}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Robot_Operate
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="P_Robot_Operate">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>