<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="P_CP1_Check" Id="{6176801c-fa9a-48a4-9f5e-14dd91aa3a80}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_CP1_Check
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="P_CP1_Check">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>